/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 java.glb -T 
Files: java.glb [3.16MB] > D:\SemVI\3dPortfolio\3d-portfolio\public\models\java-transformed.glb [142.44KB] (95%)
Author: PhantomXD (https://sketchfab.com/PhantomXD)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/java-442de0f1b8a54966bc16466b329105af
Title: Java
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/java-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <mesh name="Cube_0" geometry={nodes.Cube_0.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="Plane001_0" geometry={nodes.Plane001_0.geometry} material={materials['Material.002']} morphTargetDictionary={nodes.Plane001_0.morphTargetDictionary} morphTargetInfluences={nodes.Plane001_0.morphTargetInfluences} position={[0, 1.518, 0]} scale={1.218} />
      </group>
    </group>
  )
}

useGLTF.preload('/java-transformed.glb')
